version: '2'

services:
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile-development
    ports:
      - ${SERVER_PORT:-3033}:${SERVER_PORT:-3033}
    environment:
      - PUBSWEET_SECRET=${PUBSWEET_SECRET:-dev_secret}
      - SERVER_PORT=${SERVER_PORT:-3033}
      - SERVER_HOST=${SERVER_HOST:-localhost}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL:-http}
      - POSTGRES_USER=${POSTGRES_USER:-pagedjs_user_dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secretpassword}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB:-pagedjs_dev_db}
      - POSTGRES_PORT=5432
      - NODE_ENV=development
    security_opt:
      - seccomp:unconfined
    entrypoint:
      [
        'node_modules/.bin/wait-for-it',
        'db:5432',
        '--',
        'sh',
        'scripts/setupDevServer.sh',
      ]
    command:
      [
        'node_modules/.bin/nodemon',
        './server/startServer.js',
        '--watch',
        'server',
        '--watch',
        'config',
        '--ext',
        'js,graphql',
        '--ignore',
        '/static/*',
      ]
    volumes:
      - ./server:/home/node/pagedjs/server
      - ./config:/home/node/pagedjs/config

  db:
    image: postgres:12-alpine
    # ports:
    #   - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - ./scripts/init-pgboss.sql:/docker-entrypoint-initdb.d/init-pgboss.sql
